driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
    run_list:
     - recipe[yum::default]
  - name: centos-6.5
    run_list:
     - recipe[yum::default]
  - name: fedora-19
    run_list:
     - recipe[yum::default]
  - name: ubuntu-12.04
    run_list:
     - recipe[apt::default]
  - name: ubuntu-13.04
    run_list:
     - recipe[apt::default]
  - name: ubuntu-13.10
    run_list:
     - recipe[apt::default]
suites:
  - name: default
    run_list:
      - recipe[php::default]
  - name: apt-ondrej-repo
    excludes: ["centos-5.10", "centos-6.5", "fedora-19"]
    run_list:
      - recipe[php::apt_ondrej_ppa]
  - name: modules
    excludes: ["centos-5.10", "centos-6.5", "fedora-19"]
    run_list:
      - recipe[php::default]
      - recipe[php::module_mcrypt]
